version: '3.9'


services:
  postgres:
    image: postgres:16
    container_name: recom-postgres
    environment:
      POSTGRES_DB: recom
      POSTGRES_USER: recom
      POSTGRES_PASSWORD: recom
    ports:
      - "5432:5432"
    volumes:
      - recom-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL" , "pg_isready -U recom" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  recom-data:

