spring.application.name=sb-ecom

server.port=9090


#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomDB
spring.datasource.username=postgres
spring.datasource.password=@Ritwik12


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
project.image=images/

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=jaisdfqower9werikdnfvoijer239r0wfnsdnfasjrfr9q340uosdnmfeirljdfnugto
spring.app.jwtExpirationMs=3000000000000000000
spring.app.jwtCookieName=springBootEcom


spring.logging.level.root=INFO
spring.logging.level.com.ecommerce.project=DEBUG
spring.logging.level.org.springframework.web=TRACE
spring.logging.level.org.hibernate=ERROR



