spring.application.name=sb-ecom

server.port=5000

spring.datasource.url=${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpiration=${JWT_EXPIRATION}
spring.app.jwtCookieName=${JWT_COOKIENAME}

#upload image to s3

aws.s3.bucket=${S3_BUCKET_NAME}
aws.s3.region=${S3_BUCKET_REGION}

#STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}


my.variable=prod





