-- ============================================
-- Initial database schema
-- ============================================

-- USERS
CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(20) NOT NULL UNIQUE,
                       email VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(120) NOT NULL
);

-- ROLES
CREATE TABLE roles (
                       role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       role_name VARCHAR(20) CHECK (role_name IN ('ROLE_USER', 'ROLE_SELLER', 'ROLE_ADMIN'))
);

-- USER_ROLE
CREATE TABLE user_role (
                           role_id BIGINT NOT NULL,
                           user_id BIGINT NOT NULL,
                           PRIMARY KEY (role_id, user_id)
);

-- CATEGORIES
CREATE TABLE categories (
                            category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            category_name VARCHAR(255) NOT NULL
);

-- PAYMENTS
CREATE TABLE payments (
                          payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          payment_method VARCHAR(255) NOT NULL,
                          pg_name VARCHAR(255),
                          pg_payment_id VARCHAR(255),
                          pg_response_message VARCHAR(255),
                          pg_status VARCHAR(255)
);

-- ADDRESSES
CREATE TABLE addresses (
                           address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id BIGINT,
                           building_name VARCHAR(255) NOT NULL,
                           city VARCHAR(255) NOT NULL,
                           country VARCHAR(255) NOT NULL,
                           pin_code VARCHAR(255) NOT NULL,
                           state VARCHAR(255) NOT NULL,
                           street VARCHAR(255) NOT NULL
);

-- CARTS
CREATE TABLE carts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       total_price DOUBLE PRECISION,
                       user_id BIGINT UNIQUE
);

-- PRODUCTS
CREATE TABLE products (
                          product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_id BIGINT,
                          seller_id BIGINT,
                          description VARCHAR(255) NOT NULL,
                          image VARCHAR(255),
                          product_name VARCHAR(255) NOT NULL,
                          price DOUBLE PRECISION NOT NULL,
                          discount DOUBLE PRECISION NOT NULL,
                          quantity INTEGER,
                          special_price DOUBLE PRECISION NOT NULL
);

-- ORDERS
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        address_id BIGINT,
                        payment_id BIGINT UNIQUE,
                        total_amount DOUBLE PRECISION,
                        order_date TIMESTAMP,
                        email VARCHAR(255) NOT NULL,
                        order_status VARCHAR(255)
);

-- CART_ITEM
CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cart_id BIGINT,
                           product_id BIGINT,
                           discount DOUBLE PRECISION,
                           product_price DOUBLE PRECISION,
                           quantity INTEGER
);

-- ORDER_ITEMS
CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT,
                             product_id BIGINT,
                             discount DOUBLE PRECISION NOT NULL,
                             ordered_product_price DOUBLE PRECISION NOT NULL,
                             quantity INTEGER
);

-- ============================================
-- Foreign Keys
-- ============================================

ALTER TABLE addresses
    ADD CONSTRAINT FK_addresses_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id);

ALTER TABLE carts
    ADD CONSTRAINT FK_carts_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id);

ALTER TABLE products
    ADD CONSTRAINT FK_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories(category_id);

ALTER TABLE products
    ADD CONSTRAINT FK_products_seller
        FOREIGN KEY (seller_id)
            REFERENCES users(user_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_address
        FOREIGN KEY (address_id)
            REFERENCES addresses(address_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_orders_payment
        FOREIGN KEY (payment_id)
            REFERENCES payments(payment_id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts(id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_cart_item_product
        FOREIGN KEY (product_id)
            REFERENCES products(product_id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders(id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_order_items_product
        FOREIGN KEY (product_id)
            REFERENCES products(product_id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES roles(role_id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id);